[2025-02-15 13:58:51,306] {scheduler_job.py:182} INFO - Started process (PID=529) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 13:58:51,308] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 13:58:51,309] {logging_mixin.py:104} INFO - [2025-02-15 13:58:51,308] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 13:58:51,344] {logging_mixin.py:104} INFO - [2025-02-15 13:58:51,326] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 13:58:51,344] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 13:58:51,379] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.078 seconds
[2025-02-15 13:59:21,483] {scheduler_job.py:182} INFO - Started process (PID=591) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 13:59:21,487] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 13:59:21,490] {logging_mixin.py:104} INFO - [2025-02-15 13:59:21,489] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 13:59:21,506] {logging_mixin.py:104} INFO - [2025-02-15 13:59:21,503] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 13:59:21,506] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 13:59:21,535] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.069 seconds
[2025-02-15 13:59:51,858] {scheduler_job.py:182} INFO - Started process (PID=652) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 13:59:51,860] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 13:59:51,861] {logging_mixin.py:104} INFO - [2025-02-15 13:59:51,861] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 13:59:51,873] {logging_mixin.py:104} INFO - [2025-02-15 13:59:51,872] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 13:59:51,874] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 13:59:51,910] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.058 seconds
[2025-02-15 14:01:26,736] {scheduler_job.py:182} INFO - Started process (PID=53) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:01:26,746] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:01:26,758] {logging_mixin.py:104} INFO - [2025-02-15 14:01:26,757] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:01:26,826] {logging_mixin.py:104} INFO - [2025-02-15 14:01:26,815] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:01:26,829] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:01:26,951] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.226 seconds
[2025-02-15 14:01:57,430] {scheduler_job.py:182} INFO - Started process (PID=105) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:01:57,437] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:01:57,440] {logging_mixin.py:104} INFO - [2025-02-15 14:01:57,440] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:01:57,504] {logging_mixin.py:104} INFO - [2025-02-15 14:01:57,496] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:01:57,507] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:01:57,635] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.216 seconds
[2025-02-15 14:05:12,825] {scheduler_job.py:182} INFO - Started process (PID=53) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:05:12,839] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:05:12,841] {logging_mixin.py:104} INFO - [2025-02-15 14:05:12,840] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:05:12,928] {logging_mixin.py:104} INFO - [2025-02-15 14:05:12,926] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:05:12,930] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:05:13,074] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.384 seconds
[2025-02-15 14:07:47,532] {scheduler_job.py:182} INFO - Started process (PID=405) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:07:47,536] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:07:47,538] {logging_mixin.py:104} INFO - [2025-02-15 14:07:47,537] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:07:47,570] {logging_mixin.py:104} INFO - [2025-02-15 14:07:47,565] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:07:47,571] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:07:47,640] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.118 seconds
[2025-02-15 14:08:18,670] {scheduler_job.py:182} INFO - Started process (PID=456) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:08:18,673] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:08:18,675] {logging_mixin.py:104} INFO - [2025-02-15 14:08:18,675] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:08:18,700] {logging_mixin.py:104} INFO - [2025-02-15 14:08:18,697] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:08:18,701] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:08:18,739] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.082 seconds
[2025-02-15 14:08:48,778] {scheduler_job.py:182} INFO - Started process (PID=518) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:08:48,779] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:08:48,781] {logging_mixin.py:104} INFO - [2025-02-15 14:08:48,780] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:08:48,794] {logging_mixin.py:104} INFO - [2025-02-15 14:08:48,792] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:08:48,794] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:08:48,837] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.065 seconds
[2025-02-15 14:09:19,681] {scheduler_job.py:182} INFO - Started process (PID=580) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:09:19,682] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:09:19,683] {logging_mixin.py:104} INFO - [2025-02-15 14:09:19,683] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:09:19,690] {logging_mixin.py:104} INFO - [2025-02-15 14:09:19,689] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:09:19,691] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:09:19,715] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.038 seconds
[2025-02-15 14:09:49,931] {scheduler_job.py:182} INFO - Started process (PID=632) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:09:49,932] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:09:49,933] {logging_mixin.py:104} INFO - [2025-02-15 14:09:49,933] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:09:49,941] {logging_mixin.py:104} INFO - [2025-02-15 14:09:49,940] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:09:49,942] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:09:49,991] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.064 seconds
[2025-02-15 14:10:20,310] {scheduler_job.py:182} INFO - Started process (PID=693) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:10:20,311] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:10:20,312] {logging_mixin.py:104} INFO - [2025-02-15 14:10:20,312] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:10:20,320] {logging_mixin.py:104} INFO - [2025-02-15 14:10:20,319] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:10:20,320] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:10:20,352] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.045 seconds
[2025-02-15 14:10:50,746] {scheduler_job.py:182} INFO - Started process (PID=745) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:10:50,749] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:10:50,750] {logging_mixin.py:104} INFO - [2025-02-15 14:10:50,750] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:10:50,762] {logging_mixin.py:104} INFO - [2025-02-15 14:10:50,761] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:10:50,763] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:10:50,794] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.058 seconds
[2025-02-15 14:11:21,062] {scheduler_job.py:182} INFO - Started process (PID=804) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:11:21,063] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:11:21,064] {logging_mixin.py:104} INFO - [2025-02-15 14:11:21,064] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:11:21,072] {logging_mixin.py:104} INFO - [2025-02-15 14:11:21,071] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:11:21,072] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:11:21,098] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.039 seconds
[2025-02-15 14:11:51,842] {scheduler_job.py:182} INFO - Started process (PID=859) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:11:51,845] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:11:51,847] {logging_mixin.py:104} INFO - [2025-02-15 14:11:51,846] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:11:51,860] {logging_mixin.py:104} INFO - [2025-02-15 14:11:51,859] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:11:51,860] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:11:51,893] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.060 seconds
[2025-02-15 14:12:21,960] {scheduler_job.py:182} INFO - Started process (PID=921) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:12:21,961] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:12:21,962] {logging_mixin.py:104} INFO - [2025-02-15 14:12:21,962] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:12:21,969] {logging_mixin.py:104} INFO - [2025-02-15 14:12:21,968] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:12:21,969] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:12:21,998] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.041 seconds
[2025-02-15 14:12:52,902] {scheduler_job.py:182} INFO - Started process (PID=974) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:12:52,904] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:12:52,905] {logging_mixin.py:104} INFO - [2025-02-15 14:12:52,904] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:12:52,916] {logging_mixin.py:104} INFO - [2025-02-15 14:12:52,915] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:12:52,917] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:12:52,956] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.059 seconds
[2025-02-15 14:13:23,262] {scheduler_job.py:182} INFO - Started process (PID=1035) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:13:23,264] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:13:23,265] {logging_mixin.py:104} INFO - [2025-02-15 14:13:23,264] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:13:23,276] {logging_mixin.py:104} INFO - [2025-02-15 14:13:23,274] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:13:23,276] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:13:23,305] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.048 seconds
[2025-02-15 14:13:53,778] {scheduler_job.py:182} INFO - Started process (PID=1088) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:13:53,783] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:13:53,786] {logging_mixin.py:104} INFO - [2025-02-15 14:13:53,786] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:13:53,803] {logging_mixin.py:104} INFO - [2025-02-15 14:13:53,802] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:13:53,804] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:13:53,836] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.073 seconds
[2025-02-15 14:15:02,610] {scheduler_job.py:182} INFO - Started process (PID=52) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:15:02,619] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:15:02,623] {logging_mixin.py:104} INFO - [2025-02-15 14:15:02,622] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:15:02,699] {logging_mixin.py:104} INFO - [2025-02-15 14:15:02,695] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:15:02,701] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:15:02,834] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.259 seconds
[2025-02-15 14:15:33,154] {scheduler_job.py:182} INFO - Started process (PID=97) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:15:33,157] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:15:33,164] {logging_mixin.py:104} INFO - [2025-02-15 14:15:33,159] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:15:33,200] {logging_mixin.py:104} INFO - [2025-02-15 14:15:33,198] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:15:33,201] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:15:33,265] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.121 seconds
[2025-02-15 14:16:04,207] {scheduler_job.py:182} INFO - Started process (PID=149) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:16:04,245] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:16:04,322] {logging_mixin.py:104} INFO - [2025-02-15 14:16:04,313] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:16:04,751] {logging_mixin.py:104} INFO - [2025-02-15 14:16:04,665] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:16:04,784] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:21:09,442] {scheduler_job.py:182} INFO - Started process (PID=152) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:21:09,463] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:21:09,477] {logging_mixin.py:104} INFO - [2025-02-15 14:21:09,468] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:21:09,807] {logging_mixin.py:104} INFO - [2025-02-15 14:21:09,789] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:21:09,808] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:21:10,094] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.711 seconds
[2025-02-15 14:21:40,454] {scheduler_job.py:182} INFO - Started process (PID=204) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:21:40,468] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:21:40,472] {logging_mixin.py:104} INFO - [2025-02-15 14:21:40,471] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:21:40,527] {logging_mixin.py:104} INFO - [2025-02-15 14:21:40,524] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:21:40,531] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:21:40,697] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.263 seconds
[2025-02-15 14:22:11,146] {scheduler_job.py:182} INFO - Started process (PID=251) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:22:11,149] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:22:11,151] {logging_mixin.py:104} INFO - [2025-02-15 14:22:11,151] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:22:11,173] {logging_mixin.py:104} INFO - [2025-02-15 14:22:11,171] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:22:11,174] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:22:11,229] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.091 seconds
[2025-02-15 14:22:41,518] {scheduler_job.py:182} INFO - Started process (PID=303) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:22:41,520] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:22:41,521] {logging_mixin.py:104} INFO - [2025-02-15 14:22:41,521] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:22:41,537] {logging_mixin.py:104} INFO - [2025-02-15 14:22:41,527] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:22:41,537] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:22:41,565] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.051 seconds
[2025-02-15 14:25:00,050] {scheduler_job.py:182} INFO - Started process (PID=51) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:25:00,055] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:25:00,057] {logging_mixin.py:104} INFO - [2025-02-15 14:25:00,057] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:25:00,098] {logging_mixin.py:104} INFO - [2025-02-15 14:25:00,096] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:25:00,100] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:25:00,223] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.195 seconds
[2025-02-15 14:25:30,482] {scheduler_job.py:182} INFO - Started process (PID=96) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:25:30,493] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:25:30,499] {logging_mixin.py:104} INFO - [2025-02-15 14:25:30,498] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:25:30,539] {logging_mixin.py:104} INFO - [2025-02-15 14:25:30,534] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:25:30,541] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:25:30,807] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.351 seconds
[2025-02-15 14:26:01,299] {scheduler_job.py:182} INFO - Started process (PID=149) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:26:01,304] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:26:01,307] {logging_mixin.py:104} INFO - [2025-02-15 14:26:01,306] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:26:01,342] {logging_mixin.py:104} INFO - [2025-02-15 14:26:01,327] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:26:01,344] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:26:01,389] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.099 seconds
[2025-02-15 14:26:31,710] {scheduler_job.py:182} INFO - Started process (PID=211) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:26:31,716] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:26:31,718] {logging_mixin.py:104} INFO - [2025-02-15 14:26:31,717] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:26:31,730] {logging_mixin.py:104} INFO - [2025-02-15 14:26:31,728] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:26:31,730] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:26:31,761] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.062 seconds
[2025-02-15 14:27:01,898] {scheduler_job.py:182} INFO - Started process (PID=263) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:27:01,902] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:27:01,904] {logging_mixin.py:104} INFO - [2025-02-15 14:27:01,904] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:27:01,917] {logging_mixin.py:104} INFO - [2025-02-15 14:27:01,916] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:27:01,917] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:27:01,951] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.063 seconds
[2025-02-15 14:27:32,092] {scheduler_job.py:182} INFO - Started process (PID=325) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:27:32,093] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:27:32,095] {logging_mixin.py:104} INFO - [2025-02-15 14:27:32,094] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:27:32,107] {logging_mixin.py:104} INFO - [2025-02-15 14:27:32,106] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:27:32,108] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:27:32,137] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.052 seconds
[2025-02-15 14:28:02,621] {scheduler_job.py:182} INFO - Started process (PID=377) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:28:02,623] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:28:02,625] {logging_mixin.py:104} INFO - [2025-02-15 14:28:02,625] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:28:02,644] {logging_mixin.py:104} INFO - [2025-02-15 14:28:02,643] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:28:02,645] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:28:02,686] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.076 seconds
[2025-02-15 14:28:32,913] {scheduler_job.py:182} INFO - Started process (PID=439) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:28:32,917] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:28:32,919] {logging_mixin.py:104} INFO - [2025-02-15 14:28:32,919] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:28:32,935] {logging_mixin.py:104} INFO - [2025-02-15 14:28:32,934] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:28:32,936] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:28:32,961] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.056 seconds
[2025-02-15 14:29:03,278] {scheduler_job.py:182} INFO - Started process (PID=491) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:29:03,279] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:29:03,280] {logging_mixin.py:104} INFO - [2025-02-15 14:29:03,280] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:29:03,289] {logging_mixin.py:104} INFO - [2025-02-15 14:29:03,288] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:29:03,289] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:29:03,318] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.044 seconds
[2025-02-15 14:29:33,508] {scheduler_job.py:182} INFO - Started process (PID=549) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:29:33,511] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:29:33,523] {logging_mixin.py:104} INFO - [2025-02-15 14:29:33,513] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:29:33,560] {logging_mixin.py:104} INFO - [2025-02-15 14:29:33,556] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:29:33,561] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:29:33,699] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.210 seconds
[2025-02-15 14:30:03,794] {scheduler_job.py:182} INFO - Started process (PID=604) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:30:03,796] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:30:03,798] {logging_mixin.py:104} INFO - [2025-02-15 14:30:03,797] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:30:03,810] {logging_mixin.py:104} INFO - [2025-02-15 14:30:03,809] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:30:03,811] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:30:03,849] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.064 seconds
[2025-02-15 14:30:34,179] {scheduler_job.py:182} INFO - Started process (PID=656) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:30:34,183] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:30:34,186] {logging_mixin.py:104} INFO - [2025-02-15 14:30:34,185] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:30:34,212] {logging_mixin.py:104} INFO - [2025-02-15 14:30:34,210] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:30:34,214] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:30:34,300] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.133 seconds
[2025-02-15 14:31:04,919] {scheduler_job.py:182} INFO - Started process (PID=708) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:31:04,921] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:31:04,922] {logging_mixin.py:104} INFO - [2025-02-15 14:31:04,922] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:31:04,932] {logging_mixin.py:104} INFO - [2025-02-15 14:31:04,932] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:31:04,933] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:31:04,964] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.051 seconds
[2025-02-15 14:31:35,137] {scheduler_job.py:182} INFO - Started process (PID=770) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:31:35,139] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:31:35,139] {logging_mixin.py:104} INFO - [2025-02-15 14:31:35,139] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:31:35,147] {logging_mixin.py:104} INFO - [2025-02-15 14:31:35,146] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:31:35,148] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:31:35,180] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.049 seconds
[2025-02-15 14:32:05,603] {scheduler_job.py:182} INFO - Started process (PID=822) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:32:05,605] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:32:05,605] {logging_mixin.py:104} INFO - [2025-02-15 14:32:05,605] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:32:05,613] {logging_mixin.py:104} INFO - [2025-02-15 14:32:05,612] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:32:05,614] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:32:05,646] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.050 seconds
[2025-02-15 14:32:35,861] {scheduler_job.py:182} INFO - Started process (PID=874) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:32:35,864] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:32:35,867] {logging_mixin.py:104} INFO - [2025-02-15 14:32:35,867] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:32:35,891] {logging_mixin.py:104} INFO - [2025-02-15 14:32:35,888] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:32:35,894] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:32:35,953] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.103 seconds
[2025-02-15 14:33:06,073] {scheduler_job.py:182} INFO - Started process (PID=935) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:33:06,078] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:33:06,079] {logging_mixin.py:104} INFO - [2025-02-15 14:33:06,079] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:33:06,088] {logging_mixin.py:104} INFO - [2025-02-15 14:33:06,086] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:33:06,089] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:33:06,115] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.047 seconds
[2025-02-15 14:33:36,733] {scheduler_job.py:182} INFO - Started process (PID=988) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:33:36,734] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:33:36,735] {logging_mixin.py:104} INFO - [2025-02-15 14:33:36,734] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:33:36,741] {logging_mixin.py:104} INFO - [2025-02-15 14:33:36,740] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:33:36,741] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:33:36,772] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.043 seconds
[2025-02-15 14:34:06,792] {scheduler_job.py:182} INFO - Started process (PID=1047) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:06,793] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:34:06,794] {logging_mixin.py:104} INFO - [2025-02-15 14:34:06,794] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:06,802] {logging_mixin.py:104} INFO - [2025-02-15 14:34:06,801] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:34:06,802] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:06,829] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.040 seconds
[2025-02-15 14:34:36,903] {scheduler_job.py:182} INFO - Started process (PID=1102) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:36,905] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:34:36,906] {logging_mixin.py:104} INFO - [2025-02-15 14:34:36,905] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:36,916] {logging_mixin.py:104} INFO - [2025-02-15 14:34:36,915] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:34:36,917] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:36,949] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.051 seconds
[2025-02-15 14:34:41,562] {scheduler_job.py:182} INFO - Started process (PID=1109) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:41,564] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:34:41,567] {logging_mixin.py:104} INFO - [2025-02-15 14:34:41,566] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:41,579] {logging_mixin.py:104} INFO - [2025-02-15 14:34:41,573] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 54
    dag=dag)
      ^
SyntaxError: invalid syntax
[2025-02-15 14:34:41,580] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:41,665] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.115 seconds
[2025-02-15 14:34:45,850] {scheduler_job.py:182} INFO - Started process (PID=1123) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:45,873] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:34:45,884] {logging_mixin.py:104} INFO - [2025-02-15 14:34:45,883] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:45,933] {logging_mixin.py:104} INFO - [2025-02-15 14:34:45,931] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:34:45,935] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:34:46,131] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.318 seconds
[2025-02-15 14:36:03,661] {scheduler_job.py:182} INFO - Started process (PID=1128) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:36:03,671] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:36:03,681] {logging_mixin.py:104} INFO - [2025-02-15 14:36:03,673] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:36:05,008] {logging_mixin.py:104} INFO - [2025-02-15 14:36:04,819] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:36:06,468] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:36:19,858] {scheduler_job.py:193} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 187, in _run_file_processor
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 646, in process_file
    self.update_import_errors(session, dagbag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 537, in update_import_errors
    session.query(errors.ImportError).filter(errors.ImportError.filename == dagbag_file).delete()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3926, in delete
    delete_op.exec_()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
    self._do_exec()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1930, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
    self.result = self.query._execute_crud(stmt, self.mapper)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3565, in _execute_crud
    mapper=mapper, clause=stmt, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2025-02-15 14:38:19,005] {scheduler_job.py:182} INFO - Started process (PID=1132) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:38:19,009] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:38:19,014] {logging_mixin.py:104} INFO - [2025-02-15 14:38:19,011] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:38:19,065] {logging_mixin.py:104} INFO - [2025-02-15 14:38:19,060] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:38:19,066] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:38:19,126] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.131 seconds
[2025-02-15 14:38:49,181] {scheduler_job.py:182} INFO - Started process (PID=1184) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:38:49,183] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:38:49,185] {logging_mixin.py:104} INFO - [2025-02-15 14:38:49,184] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:38:49,203] {logging_mixin.py:104} INFO - [2025-02-15 14:38:49,201] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:38:49,205] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:38:49,260] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.087 seconds
[2025-02-15 14:41:18,276] {scheduler_job.py:182} INFO - Started process (PID=1226) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:41:20,413] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:41:21,589] {logging_mixin.py:104} INFO - [2025-02-15 14:41:21,108] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:43:08,252] {logging_mixin.py:104} INFO - [2025-02-15 14:42:41,669] {timeout.py:36} ERROR - Process timed out, PID: 1226
[2025-02-15 14:43:54,824] {logging_mixin.py:104} INFO - [2025-02-15 14:43:54,162] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 3, in <module>
    from airflow.operators.python_operator import PythonOperator
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 23, in <module>
    from airflow.operators.python import (  # noqa
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1272, in find_spec
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/weatherDag.py after 30.0s, PID: 1226
[2025-02-15 14:43:54,849] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:43:56,728] {scheduler_job.py:182} INFO - Started process (PID=1229) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:43:56,738] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:43:56,743] {logging_mixin.py:104} INFO - [2025-02-15 14:43:56,742] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:43:57,006] {logging_mixin.py:104} INFO - [2025-02-15 14:43:56,991] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:43:57,007] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:43:57,388] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.679 seconds
[2025-02-15 14:44:27,973] {scheduler_job.py:182} INFO - Started process (PID=1281) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:44:27,975] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:44:27,976] {logging_mixin.py:104} INFO - [2025-02-15 14:44:27,976] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:44:27,994] {logging_mixin.py:104} INFO - [2025-02-15 14:44:27,992] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:44:27,994] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:44:28,043] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.077 seconds
[2025-02-15 14:46:07,880] {scheduler_job.py:182} INFO - Started process (PID=44) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:46:07,883] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:46:07,889] {logging_mixin.py:104} INFO - [2025-02-15 14:46:07,888] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:46:07,935] {logging_mixin.py:104} INFO - [2025-02-15 14:46:07,930] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:46:07,957] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:46:08,036] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.171 seconds
[2025-02-15 14:46:38,207] {scheduler_job.py:182} INFO - Started process (PID=96) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:46:38,212] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:46:38,215] {logging_mixin.py:104} INFO - [2025-02-15 14:46:38,215] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:46:38,314] {logging_mixin.py:104} INFO - [2025-02-15 14:46:38,294] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:46:38,315] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:46:38,418] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.225 seconds
[2025-02-15 14:47:09,004] {scheduler_job.py:182} INFO - Started process (PID=147) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:47:09,006] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:47:09,007] {logging_mixin.py:104} INFO - [2025-02-15 14:47:09,006] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:47:09,026] {logging_mixin.py:104} INFO - [2025-02-15 14:47:09,024] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:47:09,026] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:47:09,056] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.057 seconds
[2025-02-15 14:47:39,692] {scheduler_job.py:182} INFO - Started process (PID=199) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:47:39,694] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:47:39,696] {logging_mixin.py:104} INFO - [2025-02-15 14:47:39,696] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:47:39,723] {logging_mixin.py:104} INFO - [2025-02-15 14:47:39,720] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:47:39,724] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:47:39,754] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.070 seconds
[2025-02-15 14:48:10,276] {scheduler_job.py:182} INFO - Started process (PID=261) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:48:10,280] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:48:10,281] {logging_mixin.py:104} INFO - [2025-02-15 14:48:10,281] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:48:10,307] {logging_mixin.py:104} INFO - [2025-02-15 14:48:10,305] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:48:10,308] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:48:10,365] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.095 seconds
[2025-02-15 14:48:41,100] {scheduler_job.py:182} INFO - Started process (PID=313) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:48:41,106] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:48:41,107] {logging_mixin.py:104} INFO - [2025-02-15 14:48:41,107] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:48:41,116] {logging_mixin.py:104} INFO - [2025-02-15 14:48:41,115] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:48:41,117] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:48:41,142] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.049 seconds
[2025-02-15 14:49:11,247] {scheduler_job.py:182} INFO - Started process (PID=365) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:49:11,249] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:49:11,250] {logging_mixin.py:104} INFO - [2025-02-15 14:49:11,250] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:49:11,263] {logging_mixin.py:104} INFO - [2025-02-15 14:49:11,261] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:49:11,263] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:49:11,305] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.062 seconds
[2025-02-15 14:49:41,664] {scheduler_job.py:182} INFO - Started process (PID=427) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:49:41,668] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:49:41,669] {logging_mixin.py:104} INFO - [2025-02-15 14:49:41,669] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:49:41,680] {logging_mixin.py:104} INFO - [2025-02-15 14:49:41,678] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:49:41,681] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:49:41,721] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.061 seconds
[2025-02-15 14:50:11,757] {scheduler_job.py:182} INFO - Started process (PID=479) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:50:11,758] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:50:11,759] {logging_mixin.py:104} INFO - [2025-02-15 14:50:11,759] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:50:11,768] {logging_mixin.py:104} INFO - [2025-02-15 14:50:11,767] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:50:11,769] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:50:11,795] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.044 seconds
[2025-02-15 14:50:42,144] {scheduler_job.py:182} INFO - Started process (PID=541) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:50:42,146] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:50:42,149] {logging_mixin.py:104} INFO - [2025-02-15 14:50:42,149] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:50:42,161] {logging_mixin.py:104} INFO - [2025-02-15 14:50:42,159] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:50:42,162] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:50:42,208] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.070 seconds
[2025-02-15 14:51:12,434] {scheduler_job.py:182} INFO - Started process (PID=593) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:51:12,436] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:51:12,437] {logging_mixin.py:104} INFO - [2025-02-15 14:51:12,437] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:51:12,449] {logging_mixin.py:104} INFO - [2025-02-15 14:51:12,449] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:51:12,450] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:51:12,478] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.054 seconds
[2025-02-15 14:51:42,777] {scheduler_job.py:182} INFO - Started process (PID=646) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:51:42,778] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:51:42,779] {logging_mixin.py:104} INFO - [2025-02-15 14:51:42,779] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:51:42,789] {logging_mixin.py:104} INFO - [2025-02-15 14:51:42,788] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:51:42,789] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:51:42,821] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.049 seconds
[2025-02-15 14:52:36,268] {scheduler_job.py:182} INFO - Started process (PID=698) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 14:52:36,327] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 14:52:36,341] {logging_mixin.py:104} INFO - [2025-02-15 14:52:36,340] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:52:40,136] {logging_mixin.py:104} INFO - [2025-02-15 14:52:38,478] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 14:52:42,780] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 14:52:54,300] {scheduler_job.py:193} ERROR - Got an exception! Propagating...
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 187, in _run_file_processor
    callback_requests=callback_requests,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 646, in process_file
    self.update_import_errors(session, dagbag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 537, in update_import_errors
    session.query(errors.ImportError).filter(errors.ImportError.filename == dagbag_file).delete()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3926, in delete
    delete_op.exec_()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1697, in exec_
    self._do_exec()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1930, in _do_exec
    self._execute_stmt(delete_stmt)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1702, in _execute_stmt
    self.result = self.query._execute_crud(stmt, self.mapper)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3565, in _execute_crud
    mapper=mapper, clause=stmt, close_with_result=True
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3550, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1145, in connection
    execution_options=execution_options,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1151, in _connection_for_bind
    engine, execution_options
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2025-02-15 15:12:31,582] {scheduler_job.py:182} INFO - Started process (PID=703) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 15:12:31,586] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 15:12:31,589] {logging_mixin.py:104} INFO - [2025-02-15 15:12:31,588] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:12:31,660] {logging_mixin.py:104} INFO - [2025-02-15 15:12:31,650] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 15:12:31,662] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:12:31,729] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.158 seconds
[2025-02-15 15:13:02,077] {scheduler_job.py:182} INFO - Started process (PID=755) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 15:13:02,079] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 15:13:02,081] {logging_mixin.py:104} INFO - [2025-02-15 15:13:02,081] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:13:02,105] {logging_mixin.py:104} INFO - [2025-02-15 15:13:02,103] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 15:13:02,106] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:13:02,168] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.101 seconds
[2025-02-15 15:20:23,992] {scheduler_job.py:182} INFO - Started process (PID=53) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 15:20:24,034] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 15:20:24,036] {logging_mixin.py:104} INFO - [2025-02-15 15:20:24,036] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:20:24,179] {logging_mixin.py:104} INFO - [2025-02-15 15:20:24,160] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 15:20:24,180] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:20:24,484] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.512 seconds
[2025-02-15 15:20:54,893] {scheduler_job.py:182} INFO - Started process (PID=106) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 15:20:54,932] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 15:20:54,960] {logging_mixin.py:104} INFO - [2025-02-15 15:20:54,960] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:20:55,045] {logging_mixin.py:104} INFO - [2025-02-15 15:20:55,040] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 15:20:55,057] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:20:55,301] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 0.503 seconds
[2025-02-15 15:21:25,567] {scheduler_job.py:182} INFO - Started process (PID=148) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 15:21:25,617] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 15:21:25,712] {logging_mixin.py:104} INFO - [2025-02-15 15:21:25,659] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:21:26,272] {logging_mixin.py:104} INFO - [2025-02-15 15:21:26,265] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 15:21:26,276] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:21:26,582] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 1.061 seconds
[2025-02-15 15:22:00,333] {scheduler_job.py:182} INFO - Started process (PID=192) to work on /opt/airflow/dags/weatherDag.py
[2025-02-15 15:22:00,446] {scheduler_job.py:633} INFO - Processing file /opt/airflow/dags/weatherDag.py for tasks to queue
[2025-02-15 15:22:00,457] {logging_mixin.py:104} INFO - [2025-02-15 15:22:00,457] {dagbag.py:496} INFO - Filling up the DagBag from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:22:00,731] {logging_mixin.py:104} INFO - [2025-02-15 15:22:00,660] {dagbag.py:329} ERROR - Failed to import: /opt/airflow/dags/weatherDag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/weatherDag.py", line 5, in <module>
    from src.get_weather import get_weather
ModuleNotFoundError: No module named 'src'
[2025-02-15 15:22:00,732] {scheduler_job.py:645} WARNING - No viable dags retrieved from /opt/airflow/dags/weatherDag.py
[2025-02-15 15:22:01,368] {scheduler_job.py:190} INFO - Processing /opt/airflow/dags/weatherDag.py took 1.060 seconds
